
version: "3"

services:

  backend:
    build: backend/
    image: ${REGISTRY_HOST}/${PROJECT_NAME}/backend:$IMAGE_TAG

    command: python ./main.py

    ports:
      - 8000:8000

  frontend:
    build: frontend/
    image: ${REGISTRY_HOST}/${PROJECT_NAME}/frontend:$IMAGE_TAG
    command: nginx -g 'daemon off;'

    network_mode: host

    depends_on:
      - backend

    ports:
      - 3000:3000